/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_anthonymandra_imageprocessor_ImageProcessor */

#ifndef _Included_com_anthonymandra_imageprocessor_ImageProcessor
#define _Included_com_anthonymandra_imageprocessor_ImageProcessor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_anthonymandra_imageprocessor_ImageProcessor
 * Method:    getThumbAsJpgFd
 * Signature: (I[Ljava/lang/String;I[B[III)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_anthonymandra_imageprocessor_ImageProcessor_getThumbAsJpgFd
  (JNIEnv *, jclass, jint, jobjectArray, jint, jbyteArray, jintArray, jint, jint);
  
#ifdef __cplusplus
}
#endif
#endif
